name: test
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  example:
    name: test job
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: test step
        run: ls -l
      - name: test push
        run: |
          git config --global user.name "nobody"
          git config --global user.email "username@users.noreply.github.com"
          git push origin --force HEAD:test
